
name: Python telegram bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9.9
      - run: pip install -r requirements.txt
      - run: python -m bot
        env: 
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          API_ID: ${{secrets.API_ID}}
          API_HASH: ${{secrets.API_HASH}}
          NAME_U: ${{secrets.NAME_U}}
